### ISSUE TITLE
issue with yarp rpc calibOffsets/rpc

### ISSUE THREAD

**Issue by itsjjaavii** [robotology/calibration-supervisor#16]
Hi, i'm currently trying to do the automatic calibration for red ball demo, however when i have to write in a terminal 
`yarp rpc calibOffsets/rpc` 
the terminal returns 
[ERROR] Cannot make connection
[ERROR] Alternative method: precede port name with --client
Any idea why and how can i fix this? In yarpmanager, i am able to run the calibOffsets and connect. 
Thanks in advance!

**Comment by pattacini** [comment]
>Hi, i'm currently trying to do the automatic calibration for red ball demo, however when i have to write in a terminal
yarp rpc calibOffsets/rpc

Hi @itsjjaavii 

Did you check the spelling of the port name?
It should be `/calibOffsets/rpc`.

All YARP port names begin with the leading forward slash `/`.

**Comment by itsjjaavii** [comment]
Hi @pattacini ,
i did add the slash, however, it still didn't work. I was thinking it could be because several modules doesn't work on yarpmanager, for example, skinManagerGui, all the iCubSkinGui, wholeBodyDynamics, gravityCompensator and the yarpview of the Red Ball Demo application. Is there any correlation there?

**Comment by pattacini** [comment]
Hi @itsjjaavii 

It seems that your system is somehow compromised in terms of YARP functionalities.

In this case, I would warmly suggest that you take a step back by trying the very minimal YARP setting.
You could:
- start from a clean situation where you have just power-cycled your system
- launch the YARP server
- run `yarp read /read` on a shell
- run `yarp write /write` on a second shell
- connect the two ports by running `yarp connect /write /read`
- finally, type in something in the `yarp write` shell to see if it gets transmitted to the `yarp read` shell.

**Comment by itsjjaavii** [comment]
hi @pattacini
I did what you suggested and everything worked fine. I typed something in the `yarp write` shell and it did transmitted to the `yarp read` shell, so on that part, it seems that everything it's fine. However, now I tried to execute `yarpmanager` and the terminal returned this 
![Screenshot from 2024-02-26 11-27-55](https://github.com/robotology/calibration-supervisor/assets/135467740/8c685395-e653-4644-8694-fcebe5460613)
it says that it cannot connect to /icub-head, because I don't currently have it connected to the robot. On the other hand, I don't know why it cannot connect to /icubsrv.

**Comment by itsjjaavii** [comment]
(update)
hi @pattacini , at the end, I fixed the issue related to the icubsrv (that the yarpmanager couldn't connect to /icubsrv) thanks to the discussion #659. However, the wholeBodyDynamics and gravityCompensator modules still doesn't work. 
Thank you for your patience.

**Comment by pattacini** [comment]
Hi @itsjjaavii 

Good that you found the solution by perusing our forum!

The problem seems to be unrelated to `calibration-supervisor` _per se_ then.
I would suggest the following:
- Search in the forum for similar problems. https://github.com/orgs/robotology/discussions/661 might be of help.
- If you won't find anything relevant, please post a brand new discussion at https://github.com/orgs/robotology/discussions and provide logs to help us do troubleshooting.

**Comment by itsjjaavii** [comment]
Hi @pattacini,
Thank you for your suggestions, I will do that. If I can't fix the issue, then I will post a new discussion at the link you mentioned. 
Thanks for the help :)

**Comment by pattacini** [comment]
Closing in favor of https://github.com/orgs/robotology/discussions/689.

Feel free to open it up again if deemed required.
