### ISSUE TITLE
add custom calibration file path

### ISSUE THREAD

**Issue by arrenglover** [robotology/calibration-supervisor#4]
### Overview

When performing a calibration _not_ on the robot, it would be nice to be able to specify exactly which file to use - rather than the default path and filename.

### Details

I would imagine that I can specify the filepath, and this application will use the calibration parameters in that file (e.g. board size, number of images etc.) After the calibration, that same file is populated with the calibration result - left, right, stereo. I then save the file easily with my dataset, without having concerns over exactly which file it was saved to, or which parameters were being used.

**Comment by vtikha** [comment]
@arrenglover great! we already discussed internally and this should be a quick and painless addition 👌🏼 🚀

**Comment by arrenglover** [comment]
👍 

I didn't want you to do work without having an issue to track it though 😝

**Comment by vtikha** [comment]
> 👍
> 
> I didn't want you to do work without having an issue to track it though 😝

Don't worry, there is **always** an issue that tracks the task 😉

**Comment by vvasco** [comment]
It is now possible to specify a **custom path** in the gui:

![custom](https://user-images.githubusercontent.com/9716288/109325867-ba1e4a80-7856-11eb-87a3-327185cb202d.png)

If `Custom file` is not ticked, the default file `icubEyes.ini` installed on the robot is used (this can be checked through the following command `yarp resource --context cameraCalibration --from icubEyes.ini`):

![default](https://user-images.githubusercontent.com/9716288/109325978-e2a64480-7856-11eb-9c84-910a9f9c773b.png)

**Comment by arrenglover** [comment]
Thanks Vale :clap:
