### ISSUE TITLE
1024x768 camera support?

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/calibration-supervisor#6]
Hi @vvasco @vtikha, we recently installed on iCub3 a pair of cameras with 1024x768 resolution. Since I have very little expertise in calibrating the cameras, this tool seemed pretty interesting. 

Would it be possible to use this tool at the 1024x768 resolution? Also, I am not sure we have the cameras in Gazebo for this kind of robot, so I am not sure if it is feasible or not.

**Comment by vvasco** [comment]
Hi @S-Dafarra, at the moment we don't handle the 1024x768 resolution, but we could extend the application to include this resolution. 
We would need to generate the images in Gazebo, but I'm not currently aware of the status of the cameras on iCub3 in Gazebo. We can investigate and let you know.

**Comment by S-Dafarra** [comment]
I think there is no Gazebo model of iCub3 with the cameras yet (cc @Nicogene @traversaro). Also, these cameras have been installed very recently, so also the availability of configuration files in general is very limited.

**Comment by vtikha** [comment]
Maybe @triccyx and @pattacini can also give pointers.

**Comment by pattacini** [comment]
Conf files are here: https://github.com/dic-iit/robots-configuration/tree/devel_iCubGenova09/iCubGenova09.
This is the DIC fork.

My hunch is that @S-Dafarra you may go with the old style calibration (I believe the SW can be adapted to any resolution) to speed things up and then later refinements can be done via the new procedure.

**Comment by vtikha** [comment]
Thanks for the conf files, as you wish, but in any case we will proceed with the generation of all the necessary files to be able to run the application with `1024x768`.

**Comment by pattacini** [comment]
>Thanks for the conf files, as you wish, but in any case we will proceed with the generation of all the necessary files to be able to run the application with 1024x768.

Super 👍🏻 

@vtikha don't you need the Gazebo part as well?
I thought yes and this is the main impediment as updating Gazebo is not a walk in the park yet; well, maybe not that tough, but it still requires some effort.

If not, even better! In the latter case, I would recommend that @S-Dafarra waits for the new procedure then.

**Comment by S-Dafarra** [comment]
Just to understand, does the Gazebo part needs the entire robot model, or only the presence of the two cameras? In the latter case, the iCub3 head is a normal iCub head, so I suppose that a "normal" iCub model could work, right?

**Comment by pattacini** [comment]
> Just to understand, does the Gazebo part needs the entire robot model, or only the presence of the two cameras? In the latter case, the iCub3 head is a normal iCub head, so I suppose that a "normal" iCub model could work, right?

@AlexAntn you're working with the iCub 3 Gazebo model these days; can you confirm whether the cameras are already available?

**Comment by Nicogene** [comment]
> I think there is no Gazebo model of iCub3 with the cameras yet (cc @Nicogene @traversaro).

I can confirm that, we added just the realsense device in the chest, but I don't think it would be difficult to do it

**Comment by vvasco** [comment]
> Just to understand, does the Gazebo part needs the entire robot model, or only the presence of the two cameras? In the latter case, the iCub3 head is a normal iCub head, so I suppose that a "normal" iCub model could work, right?

Yes, for the Gazebo part only the two cameras are strictly required. So the normal iCub model with the correct resolution should be fine.

**Comment by S-Dafarra** [comment]
Hi all, is there any news on this?

**Comment by vvasco** [comment]
Hi @S-Dafarra, we included the support for 1024x768 resolution within the pipeline. We would need to do a full test on iCub3 as we were having issues with that specific setup since it was relying on the server for mounting the code. Do you still use the server?
We can plan to do the test next week if that's ok with you.

**Comment by S-Dafarra** [comment]
> Hi @S-Dafarra, we included the support for 1024x768 resolution within the pipeline. We would need to do a full test on iCub3 as we were having issues with that specific setup since it was relying on the server for mounting the code. Do you still use the server?
> We can plan to do the test next week if that's ok with you.

Great @vvasco, thanks! Which server are you referring to?

**Comment by vvasco** [comment]
Great @S-Dafarra , so we'll find a spot for next week. 
I'm referring to the nfs one from which the icub software was mounted.

**Comment by S-Dafarra** [comment]
> Great @S-Dafarra , so we'll find a spot for next week.

That would be nice! We just need to organize as the robot might be needed for some interventions by team Fix. Instead, I will be available only until Tuesday, but I think this is not blocking.

> I'm referring to the nfs one from which the icub software was mounted.

Ah, no. We updated the PC and the robot to Ubuntu 20 and we don't need to mount the server anymore.

**Comment by vvasco** [comment]
Hi @S-Dafarra, unfortunately we could not perform the calibration, as we had issues when running the right camera (left camera was fine): the image starts blinking and then it becomes black.
We opened an [issue](https://github.com/robotology/icub-tech-support/issues/1200) on icub-tech-support.

**Comment by vvasco** [comment]
Hi @S-Dafarra, I know that you are already aware of the current status of this activity, but just to keep track, after the [cable was replaced](https://github.com/robotology/icub-tech-support/issues/1200#issuecomment-930032483), we could successfully calibrate the cameras and the file with the correct parameters is already in the correct path.
So I would close this issue.

The calibration should be done only once, but if for any reason you need to improve / re-calibrate, we can show you how to run the application. If you want, we could find a spot next week. 

cc @vtikha @valegagge @lauracavaliere @ilaria-carlini

**Comment by S-Dafarra** [comment]
> Hi @S-Dafarra, I know that you are already aware of the current status of this activity, but just to keep track, after the [cable was replaced](https://github.com/robotology/icub-tech-support/issues/1200#issuecomment-930032483), we could successfully calibrate the cameras and the file with the correct parameters is already in the correct path. So I would close this issue.
> 
> The calibration should be done only once, but if for any reason you need to improve / re-calibrate, we can show you how to run the application. If you want, we could find a spot next week.
> 
> cc @vtikha @valegagge @lauracavaliere @ilaria-carlini

Thanks a lot! We already used it and it is working fine! Closing
